name: 'Send Webhook'
description: '通过 Python 脚本发送自定义 webhook（支持飞书卡片）'
author: 'ChenYB0'
inputs:
  base_image:
    description: 'Docker base image（可选，默认为 python:3.9-slim）'
    required: false
    default: 'python:3.9-slim'
  url:
    description: 'Webhook 地址'
    required: true
  bot:
    description: '机器人类型（如 feishu）'
    required: false
    default: 'feishu'
  title:
    description: '标题'
    required: true
  subtitle:
    description: '副标题'
    required: false
    default: ''
  payload:
    description: '内容'
    required: true
  msg_type:
    description: '类型 info|success|warning|error'
    required: false
    default: 'info'
runs:
  using: 'docker'
  image: 'Dockerfile'
  build-args:
    BASE_IMAGE: ${{ inputs.base_image }}
  args:
    - '--url'
    - '${{ inputs.url }}'
    - '--bot'
    - '${{ inputs.bot }}'
    - '--title'
    - '${{ inputs.title }}'
    - '--subtitle'
    - '${{ inputs.subtitle }}'
    - '--payload'
    - '${{ inputs.payload }}'
    - '--msg_type'
    - '${{ inputs.msg_type }}' 
branding:
  icon: refresh-cw
  color: green